version: "3.1"
services:
    demo:
        image: ver-id-browser-demo:latest
        depends_on: 
            - scanner
            - detcv
            - recauth
        environment: 
            - PORT=8080
            - DETCV_URL=http://detcv:8080
            - RECAUTH_URL=http://recauth:8814
            - ID_SCANNER_URL=http://scanner:8080
        ports:
            - "8080:8080"
    scanner:
        image: 725614911995.dkr.ecr.us-east-1.amazonaws.com/id_scanner:1.34.0
        environment:
            - USER=microblink
            - LICENSEE=AppliedRecognitionTest
            - LICENSE_KEY=sRwAAAUWYXBwbGllZHJlY29nbml0aW9udGVzdOXQmqkzGn4pkvCFJCbQ87noe1jm/lT3ZvnsnHqWiQ5JWV3MvYptu702/N7YafpnNHh67r5M3BuT2OWm8JsTk+SsoclpS0iTNNr+93MgNAwmSz4Nfp6z5NNfNSUkTN6DrQ3oq78BZ3vuzNqdcUGYQcUnPbqq3dn292N4CB2CV1e7bWO2k6/pwfqeeYnoTfJy7Aeh7dMbgwQVfBu+go6ZAIiTEdOO+OmqrgV8pCBfhbo8pOaSn0ReN2cBgJbridUqwVzU+2SJvqjPPbmNkyzHd9hNaasSndrdb1LpKscsDEJNagpKu9HsWBAzgYoNePdgd8uvRrFHMKKcfK9V
            - PORT=8083
            - PROXY_PORT=8080
        ports:
            - "8083:8080"
    detcv:
        image: 725614911995.dkr.ecr.us-east-1.amazonaws.com/restful-servers_detcv:1.3.3
        ports:
            - "8084:8080"
    recauth:
        image: 725614911995.dkr.ecr.us-east-1.amazonaws.com/restful-servers_recauth:1.3.3
        entrypoint: [ "./fb-recauth", "--foreground" ]
        ports:
            - "8085:8814"